language: python

python:
    - "2.7"

install:
    - pip install -r requirements.txt

addons:
    postgresql: "9.3"

env:
    global:
        - DATABASE_URL=postgres://postgres@localhost:5432/codesy
        - DJANGO_SECRET_KEY=terrible-awful-secret-only-for-travis
        - DJANGO_DEBUG=True

before_script:
    - psql -c 'create database codesy;' -U postgres

script:
    - python manage.py test

deploy:
    provider: heroku
    app: codesy-dev
    api_key:
        secure: "E4RIDpJCwxI7oW7En2CeCOmw/X13DV2ePM0RWoknBgvvnmoMKYhMjdisk8FQWzVWKM9rjkHTyn8hBbzAqtTzf5xttB4wxtlOs4444W3RKGP4g/G+IIe4EtxzLc5zqPcsMefRtSMABPbVTHP0tqjYWtX7nuutYPv1/a3gyoF2Aw0="

after_deploy:
    - heroku config:set COMMIT_HASH=$TRAVIS_COMMIT --app codesy-dev

notifications:
    irc:
        channels:
            - "irc.freenode.net#codesy"
        on_success: always
        on_failure: always
        use_notice: true
