language: python

python:
    - "2.6"
    - "2.7"

install:
    - pip install -r requirements.txt

addons:
    postgresql: "9.3"

env:
    - DATABASE_URL=postgres://postgres@localhost:5432/codesy
    - DJANGO_SECRET_KEY=ht)u5#+5k)d*whz)yso6$lu$x^-2_roc40-671j^9by0r-fd@0
    - DJANGO_DEBUG=True

before_script:
    - psql -c 'create database codesy;' -U postgres

script:
    - python manage.py test

notifications:
    irc:
        channels:
            - "irc.freenode.net#codesy"
        on_success: always
        on_failure: always
        use_notice: true
