language: python

python:
    - "2.6"
    - "2.7"

install:
    - pip install -r requirements.txt

addons:
    postgresql: "9.3"

env:
    global:
        - DATABASE_URL=postgres://postgres@localhost:5432/codesy
        - DJANGO_SECRET_KEY=terrible-awful-secret-only-for-travis
        - DJANGO_DEBUG=True

before_script:
    - psql -c 'create database codesy;' -U postgres

script:
    - python manage.py test

deploy:
    provider: heroku
    app: codesy-dev
    api_key:
        secure: cFXVUU3C3RJkuXG/7aJzkCdl31fnmyP1zKCmCy80ciRSfEKlvxHjUNbOKXtkM7qqErvh9ga+lOkrlM5g2FllWNS1JLX6X2yzlAS407Y/yUf7AHmgzhcZzG5s2ToxpMews0Y+vxEsZMjRSxXGWs06G5F+0md4iE2fA8X6fLotwp4=

notifications:
    irc:
        channels:
            - "irc.freenode.net#codesy"
        on_success: always
        on_failure: always
        use_notice: true
